<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Eco.ReferenceAssemblies" />
      <PackageReference Include="K4os.Compression.LZ4"/>
      <PackageReference Include="K4os.Compression.LZ4.Legacy"/>
      <PackageReference Include="K4os.Compression.LZ4.Streams"/>
      <PackageReference Include="Newtonsoft.Json"/>
  </ItemGroup>

</Project>
